/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agecalculator;
import java.util.*;
import javax.swing.JOptionPane;
//import Java.*;
/**
 *
 * @author gulshaneng
 */

public class AgeCalculator extends javax.swing.JFrame {

   /**
     * Creates new form AgeCalculator
     */
    public AgeCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        age = new javax.swing.JButton();
        day = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        Calendar cal = Calendar.getInstance();
        year = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fday = new javax.swing.JLabel();
        fmonth = new javax.swing.JLabel();
        fyear = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tyear = new javax.swing.JComboBox();
        tmonth = new javax.swing.JComboBox();
        tday = new javax.swing.JComboBox();
        currentday = new javax.swing.JToggleButton();
        dobday = new javax.swing.JToggleButton();
        currentdayresult = new javax.swing.JLabel();
        dobdayresult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Age Calculator");
        setBackground(new java.awt.Color(240, 27, 94));
        setForeground(new java.awt.Color(204, 0, 0));
        setMinimumSize(new java.awt.Dimension(400, 320));
        setName("age"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 382));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Date Of Birth");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("dob");

        age.setForeground(new java.awt.Color(255, 51, 153));
        age.setText("Find Age");
        age.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 102)));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, 40));

        //day.addItem(cal.get(Calendar.DATE));
        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 71, 60, -1));
        day.getAccessibleContext().setAccessibleName("");

        for(int i=1;i<=12;i++)
        month.addItem(i);
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 72, -1));
        month.getAccessibleContext().setAccessibleName("");

        for(int i=cal.get(Calendar.YEAR);i>=1900;i--)
        year.addItem(i);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 71, 64, -1));
        year.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("Parry Hotter", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Day");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 60, 37));

        jLabel3.setFont(new java.awt.Font("Parry Hotter", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Year");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 24, 55, 47));

        jLabel4.setFont(new java.awt.Font("Parry Hotter", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Month");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 11, 76, 47));

        fday.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        fday.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(fday, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 90, 30));
        fday.getAccessibleContext().setAccessibleName("fday");

        fmonth.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        fmonth.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(fmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 90, 30));
        fmonth.getAccessibleContext().setAccessibleName("fmonth");

        fyear.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        fyear.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(fyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 90, 30));
        fyear.getAccessibleContext().setAccessibleName("fyear");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Your Age Is");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Till Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        for(int i=cal.get(Calendar.YEAR);i>=1900;i--)
        tyear.addItem(i);
        tyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyearActionPerformed(evt);
            }
        });
        getContentPane().add(tyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 64, -1));

        for(int i=1;i<=12;i++)
        tmonth.addItem(i);
        tmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmonthActionPerformed(evt);
            }
        });
        getContentPane().add(tmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 72, -1));

        //tday.addItem(cal.get(Calendar.DATE));
        tday.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdayActionPerformed(evt);
            }
        });
        getContentPane().add(tday, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 60, -1));

        currentday.setText("Day");
        currentday.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                currentdayItemStateChanged(evt);
            }
        });
        getContentPane().add(currentday, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 60, -1));

        dobday.setText("Day");
        dobday.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dobdayItemStateChanged(evt);
            }
        });
        dobday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dobdayStateChanged(evt);
            }
        });
        dobday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobdayActionPerformed(evt);
            }
        });
        dobday.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                dobdayVetoableChange(evt);
            }
        });
        getContentPane().add(dobday, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 110, 60, -1));
        getContentPane().add(currentdayresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 90, 20));
        getContentPane().add(dobdayresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
      
    }//GEN-LAST:event_yearActionPerformed
static int Day,Month,Year;
    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
 int birthDay, birthMonth, birthYear,currentDay,currentMonth,currentYear;

currentDay=(int)tday.getSelectedItem();
currentMonth=(int)tmonth.getSelectedItem();
currentYear=(int)tyear.getSelectedItem();

birthDay=(int)day.getSelectedItem();
birthMonth=(int)month.getSelectedItem();
birthYear=(int)year.getSelectedItem();
if(birthYear>currentYear)
{
     JOptionPane.showMessageDialog(null,"Invalid Year");
       fday.setText(" ");
        fmonth.setText(" ");
        fyear.setText(" ");
     
}
else{
        if(birthMonth >currentMonth)
        {
            if(birthDay==currentDay || birthDay < currentDay)
            {
                if(birthYear == currentYear)
                { 
                    JOptionPane.showMessageDialog(null,"Invalid Date");
                 }
                else
                    { 
                   Day = currentDay-birthDay;
                    Month = currentMonth+12-birthMonth;
                    Year = (currentYear-1)-birthYear;
                    }
            }
            else if(birthDay>currentDay)
                {
                Day =(currentDay+30)-birthDay;
                Month =((currentMonth-1)+12)-birthMonth;
              Year = (currentYear-1)-birthYear;
                }
        }
         else if(birthMonth<currentMonth || birthMonth==currentMonth)
         {
           if(birthDay<currentDay ||birthDay==currentDay)
           {
               Day =currentDay-birthDay;
                Month = currentMonth-birthMonth;
                Year= currentYear-birthYear;
           }
           else
           {
                Day=currentDay+30-birthDay;
                Month = currentMonth-1-birthMonth;
                Year = currentYear-birthYear;
           }
          }
        if(Day== 0 && Month == 0)
        {
           Happy h=new Happy();
           h.setVisible(true);
           this.dispose();
        }
        if(Month==-1){
            Month = 11;
            Year = Year - 1;
               }
        fday.setText(""+Day+" Day");
        fmonth.setText(""+Month+" Month");
        fyear.setText(""+Year+" Year");
}
    }//GEN-LAST:event_ageActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
switch(month.getSelectedIndex())
{
    case 0:
        case 2:
            case 4:
                case 6:
                    case 7:
                        case 9:
                            case 11:
                                day.removeAllItems();
                                for(int i=1;i<=31;i++)                           
                                day.addItem(i);
                            break;
     case 3:
        case 5:
            case 8:
                case 10:
                        day.removeAllItems();
                        for(int i=1;i<=30;i++)                        
                        day.addItem(i);
                break;
                    case 1:
                         day.removeAllItems();
                         if((((int)year.getSelectedItem())%4==0 && ((int)year.getSelectedItem())%100!=0 )||((int)year.getSelectedItem())%400==0)
                         {
                              for(int i=1;i<=29;i++)                        
                            day.addItem(i);
                         }
                         else
                         {
                            for(int i=1;i<=28;i++)                        
                            day.addItem(i);
                         }
                            break;
                    default:
                         day.removeAllItems();
                            for(int i=1;i<=31;i++)                           
                            day.addItem(i);
                        
}
    }//GEN-LAST:event_monthActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void tyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyearActionPerformed

    private void tmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmonthActionPerformed
        switch(tmonth.getSelectedIndex())
{
    case 0:
        case 2:
            case 4:
                case 6:
                    case 7:
                        case 9:
                            case 11:
                                tday.removeAllItems();
                                for(int i=1;i<=31;i++)                           
                                tday.addItem(i);
                            break;
     case 3:
        case 5:
            case 8:
                case 10:
                        tday.removeAllItems();
                        for(int i=1;i<=30;i++)                        
                        tday.addItem(i);
                break;
                    case 1:
                         tday.removeAllItems();
                         if((((int)tyear.getSelectedItem())%4==0 && ((int)tyear.getSelectedItem())%100!=0 )||((int)tyear.getSelectedItem())%400==0)
                         {
                              for(int i=1;i<=29;i++)                        
                            tday.addItem(i);
                         }
                         else
                         {
                            for(int i=1;i<=28;i++)                        
                            tday.addItem(i);
                         }
                            break;
                    default:
                         tday.removeAllItems();
                            for(int i=1;i<=31;i++)                           
                            tday.addItem(i);
                        
}
    }//GEN-LAST:event_tmonthActionPerformed

    private void tdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdayActionPerformed

    private void dobdayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dobdayStateChanged
 
    // TODO add your handling code here:
    }//GEN-LAST:event_dobdayStateChanged

    private void dobdayVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_dobdayVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dobdayVetoableChange

    private void dobdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobdayActionPerformed

    private void dobdayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dobdayItemStateChanged
        int state = evt.getStateChange();
     int d1, m1,y1;
        d1=(int)day.getSelectedItem();
        m1=(int)month.getSelectedItem();
        y1=(int)year.getSelectedItem();
        if (state == evt.SELECTED) { 
         int t[] = { 0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4 };
         String[] day={"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"};
        if(m1<3)
	y1 -= 1;
	dobdayresult.setText(day[(y1 + y1/4 - y1/100 + y1/400 + t[m1-1] + d1) % 7]);
	              
        } else {
          dobdayresult.setText(" ");
        }
       
   // TODO add your handling code here:
    }//GEN-LAST:event_dobdayItemStateChanged

    private void currentdayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_currentdayItemStateChanged
 int state = evt.getStateChange();
    int d2, m2,y2;      
 d2=(int)tday.getSelectedItem();
        m2=(int)tmonth.getSelectedItem();
        y2=(int)tyear.getSelectedItem();
        if (state == evt.SELECTED) { 
         int t[] = { 0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4 };
         String[] day={"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"};
        if(m2<3)
	y2 -= 1;
	currentdayresult.setText(day[(y2 + y2/4 - y2/100 + y2/400 + t[m2-1] + d2) % 7]);
	               
        } else {
         currentdayresult.setText(" ");
        }      // TODO add your handling code here:
    }//GEN-LAST:event_currentdayItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgeCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton age;
    private javax.swing.JToggleButton currentday;
    private javax.swing.JLabel currentdayresult;
    private javax.swing.JComboBox day;
    private javax.swing.JToggleButton dobday;
    private javax.swing.JLabel dobdayresult;
    private javax.swing.JLabel fday;
    private javax.swing.JLabel fmonth;
    private javax.swing.JLabel fyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox month;
    private javax.swing.JComboBox tday;
    private javax.swing.JComboBox tmonth;
    private javax.swing.JComboBox tyear;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables

}
